### ISSUE TITLE
Delay to detect protocol

### ISSUE THREAD

**Issue by nassimabedi** [mushorg/go-dpi#42]
This issue happened sometimes (I had delay to display logs) .In my test just detected ICMP protocol.  I had this log `Packet #number: Could not identify` for other protocols.

**Comment by glaslos** [comment]
Can you explain what you are expecting and what the actual outcome is?

**Comment by nassimabedi** [comment]
@glaslos I expected when runnig `./godpi_example -device <devicename>` detect all protocols. in my test was not detected. 
This is my result:
`Packet #2994: Could not identify (new flow)
Packet #2995: Detected protocol DNS from source go-dpi
Packet #2996: Detected protocol DNS from source go-dpi
Packet #2997: Could not identify (new flow)
Packet #2998: Could not identify (new flow)
Packet #2999: Detected protocol DNS from source go-dpi
Packet #3000: Detected protocol DNS from source go-dpi
Packet #3001: Could not identify (new flow)
Packet #3002: Could not identify (new flow)
Packet #3003: Detected protocol DNS from source go-dpi
Packet #3004: Detected protocol DNS from source go-dpi
Packet #3005: Could not identify (new flow)
Packet #3006: Could not identify (new flow)
Packet #3007: Could not identify (new flow)
Packet #3008: Could not identify (new flow)
Packet #3009: Detected protocol DNS from source go-dpi
Packet #3010: Detected protocol DNS from source go-dpi
Packet #3011: Could not identify (new flow)
Packet #3012: Could not identify (new flow)
Packet #3013: Could not identify (new flow)
Packet #3014: Could not identify (new flow)
Packet #3015: Could not identify (new flow)
Packet #3016: Could not identify (new flow)
`

**Comment by nassimabedi** [comment]
@glaslos maybe my installation is not completed because when I run this command `go test . ./modules/wrappers ./modules/classifiers ./types ./utils` the result is
`ok  	github.com/mushorg/go-dpi	0.362s
ok  	github.com/mushorg/go-dpi/modules/wrappers	0.185s
--- FAIL: TestClassifiers (0.01s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 13 [running]:
testing.tRunner.func1(0xc420056410)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x5cb200, 0x93fb40)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/mushorg/go-dpi/vendor/github.com/google/gopacket/layers.decodeName(0xc420090a3e, 0x478, 0x478, 0x3e05, 0xc420045ac0, 0x2, 0x32, 0x80, 0x49dcc8, 0xc420045808, ...)
	/root/go/src/github.com/mushorg/go-dpi/vendor/github.com/google/gopacket/layers/dns.go:427 +0x870
github.com/mushorg/go-dpi/vendor/github.com/google/gopacket/layers.decodeName(0xc420090a3e, 0x478, 0x478, 0xb9, 0xc420045ac0, 0x1, 0x200, 0xc421163600, 0x0, 0xb5, ...)
	/root/go/src/github.com/mushorg/go-dpi/vendor/github.com/google/gopacket/layers/dns.go:477 +0x4ac
github.com/mushorg/go-dpi/vendor/github.com/google/gopacket/layers.(*DNSQuestion).decode(0xc420045940, 0xc420090a3e, 0x478, 0x478, 0xb9, 0x947660, 0xc42110d6b0, 0xc420045ac0, 0xb9, 0x0, ...)
	/root/go/src/github.com/mushorg/go-dpi/vendor/github.com/google/gopacket/layers/dns.go:503 +0x6f
github.com/mushorg/go-dpi/vendor/github.com/google/gopacket/layers.(*DNS).DecodeFromBytes(0xc420045a18, 0xc420090a3e, 0x478, 0x478, 0x947660, 0xc42110d6b0, 0x0, 0x5)
	/root/go/src/github.com/mushorg/go-dpi/vendor/github.com/google/gopacket/layers/dns.go:241 +0x2de
github.com/mushorg/go-dpi/modules/classifiers.DNSClassifier.HeuristicClassify.func1(0x949ce0, 0xc4211ce200, 0x949ce0)
	/root/go/src/github.com/mushorg/go-dpi/modules/classifiers/dns.go:17 +0x10b
github.com/mushorg/go-dpi/modules/classifiers.checkFlowLayer(0xc4211bf500, 0x2d, 0x62b6c0, 0xc421208800)
	/root/go/src/github.com/mushorg/go-dpi/modules/classifiers/classifiers.go:109 +0xb8
github.com/mushorg/go-dpi/modules/classifiers.DNSClassifier.HeuristicClassify(0xc4211bf500, 0x41010d)
	/root/go/src/github.com/mushorg/go-dpi/modules/classifiers/dns.go:22 +0x43
github.com/mushorg/go-dpi/modules/classifiers.(*DNSClassifier).HeuristicClassify(0xea1638, 0xc4211bf500, 0xea1638)
	<autogenerated>:2 +0x4f
github.com/mushorg/go-dpi/modules/classifiers.(*ClassifierModule).ClassifyFlow(0xc420045c90, 0xc4211bf500, 0xc420045c01, 0xc42120d001, 0xc42120d0d0, 0x6)
	/root/go/src/github.com/mushorg/go-dpi/modules/classifiers/classifiers.go:76 +0xed
github.com/mushorg/go-dpi/modules/classifiers.getPcapDumpProtoMap(0x62745e, 0x25, 0x60fd53)
	/root/go/src/github.com/mushorg/go-dpi/modules/classifiers/classifiers_test.go:124 +0x4b0
github.com/mushorg/go-dpi/modules/classifiers.TestClassifiers(0xc420056410)
	/root/go/src/github.com/mushorg/go-dpi/modules/classifiers/classifiers_test.go:157 +0x123
testing.tRunner(0xc420056410, 0x62b738)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
FAIL	github.com/mushorg/go-dpi/modules/classifiers	0.160s
ok  	github.com/mushorg/go-dpi/types	0.755s
ok  	github.com/mushorg/go-dpi/utils	0.163s
`

**Comment by nikofil** [comment]
This was actually a bug in the gopacket library that was fixed in a newer version, I used to have a check in place to prevent it but removed it now that it's fixed, you just have to delete the gopacket package and do glide install again. :)
By the way, I was looking at your pcap dumps, and they didn't contain any actual HTTP traffic, just random TCP, so I'm not sure if there's something wrong with the library. I can imagine RDP possibly going undetected, but HTTP really shouldn't be like that.

**Comment by nassimabedi** [comment]
@nikofil I removed gopacket and It works for me. Thank you  :slightly_smiling_face:
I have a issue. When I start attacking to protocols it takes about one minute delay to display logs in terminal.
I use VM. Does delay probably because of that?

**Comment by nikofil** [comment]
Hmm, the VM complicates things a bit.
Do you open the browser inside the VM or outside? Also, how do you run the library from the command line?
Could you run `ifconfig` inside the VM so we can see what interfaces you have up?

**Comment by nassimabedi** [comment]
I opened the browser either outside the VM or inside the VM. I had delay most of the time.
I used this commadn to run go-dpi `./godpi_example -device ens33`
This is the result of `ifconfig` command:
````
ens33     Link encap:Ethernet  HWaddr 00:0c:29:be:12:31  
          inet addr:192.168.58.152  Bcast:192.168.58.255  Mask:255.255.255.0
          inet6 addr: fe80::2d21:fbba:fec4:1fde/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:96838 errors:0 dropped:0 overruns:0 frame:0
          TX packets:59534 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:87925109 (87.9 MB)  TX bytes:4595419 (4.5 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:3176 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3176 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:334715 (334.7 KB)  TX bytes:334715 (334.7 KB)
```

**Comment by nassimabedi** [comment]
in my tests sometimes when run go-dpi not detected protocol and after some minutes return this 
`Get https://raw.githubusercontent.com/wiki/mushorg/go-dpi/2grams_tcp.model: dial tcp: i/o timeout`
or 
`Get https://raw.githubusercontent.com/wiki/mushorg/go-dpi/2grams_tcp.model: net/http: TLS handshake timeout`

**Comment by nikofil** [comment]
It looks like it doesn't have internet access in your VM? If this is intended, you can disable the SVC module that was added recently so that it doesn't need to download the model files. You can do that either with `godpi.SetModules` or by commenting out line 17 in godpi.go.

**Comment by nassimabedi** [comment]
Yes, VM didn't access internet, I disabled SVC module and it worked.  Thank you  :slightly_smiling_face:

**Comment by nikofil** [comment]
Closing this forgotten issue, as it's solved
