### ISSUE TITLE
How to build go-dpi

### ISSUE THREAD

**Issue by nassimabedi** [mushorg/go-dpi#44]
I want to add new protocol. I done according to installation but I don't know how to build new change in do-dpi. I used this command `go test . ./modules/wrappers ./modules/classifiers ./types ./utils`  but it didn't work for me because I changed string `Could not identify` but it didn't changed.

Thanks

**Comment by nikofil** [comment]
Try running `go install ./godpi_example` in the base dir of the project.

**Comment by nassimabedi** [comment]
@nikofil Thank you 🙂

**Comment by goish135** [comment]
**Can't build go-dpi !** 

py@py:~/go-dpi$ go install ./godpi_example
go: finding github.com/patrickmn/go-cache v2.1.0+incompatible
go: finding github.com/google/gopacket v1.1.17
go: finding github.com/pkg/errors v0.9.1
go: github.com/patrickmn/go-cache@v2.1.0+incompatible: git fetch -f https://github.com/patrickmn/go-cache refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/py/go/pkg/mod/cache/vcs/b05cbb7d90cdcbcfa5ac7177241e1094d83905685f8d4e38824e0a1c9dba126d: exit status 255:
	error: cannot open FETCH_HEAD: Permission denied
go: github.com/pkg/errors@v0.9.1: git fetch -f https://github.com/pkg/errors refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/py/go/pkg/mod/cache/vcs/9b57de15915a2564a133192909d2d779433a38d49df7d581dc764e6764a41406: exit status 255:
	error: cannot open FETCH_HEAD: Permission denied
go: github.com/google/gopacket@v1.1.17: git fetch -f https://github.com/google/gopacket refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/py/go/pkg/mod/cache/vcs/884b3fc6cea4330f5869de61601125f1419c44383bebe94c2548af458d4fcabd: exit status 255:
	error: cannot open FETCH_HEAD: Permission denied
go: error loading module requirements

**Comment by glaslos** [comment]
As mentioned in #63 this is a permission issue: `error: cannot open FETCH_HEAD: Permission denied`
