### ISSUE TITLE
Measure throughput

### ISSUE THREAD

**Issue by nassimabedi** [mushorg/go-dpi#48]
Is there any way to measure throughput for each protocols in go-dpi?
Thank you 🙂

**Comment by nikofil** [comment]
Do you mean a way to measure how many packets of a protocol pass through per second? If so there isn't, but this probably should be part of the application using the library and not the library itself.

**Comment by nassimabedi** [comment]
Yes, That's exactly what I meant. Thank you :slightly_smiling_face:

**Comment by nikofil** [comment]
Glad to help. :)
