### ISSUE TITLE
gopacket.Packet is treated like a struct, is an interface

### ISSUE THREAD

**Issue by smithjacobj** [mushorg/go-dpi#49]
There are a lot of `*gopacket.Packet` where it seems just using the bare interface would be simpler and just as effective as a pointer to an interface. The documentation specifically refers to `gopacket.Packet` as a structure instead of an interface, so I'm wondering if there's a misunderstanding that lead to the use of pointers instead.

**Comment by nikofil** [comment]
You're right, I was under the impression that it's a struct and not an interface, so I was passing pointers around for efficiency. I'll remove the pointers in a bit.
