### ISSUE TITLE
source IP?

### ISSUE THREAD

**Issue by nassimabedi** [mushorg/go-dpi#51]
Is there any way to find source IP in logs?

**Comment by nikofil** [comment]
Do you mean in the example app? Currently no, but you can add the following code in the main loop (below `for packet := range packetChannel`) to print source and dest IPs:
```
		if pktNetLayer, ok := packet.NetworkLayer().(*layers.IPv4); ok {
			fmt.Printf("%s -> %s\n", pktNetLayer.SrcIP, pktNetLayer.DstIP)
		}
```

**Comment by nassimabedi** [comment]
Yes I mean in example app. It is work. Thank you  slightly_smiling_face
