### ISSUE TITLE
Identification of flows based on network ports

### ISSUE THREAD

**Issue by MrSuicideParrot** [mushorg/go-dpi#53]
I was analyzing the implementation of  the [GetFlowForPacket](https://github.com/mushorg/go-dpi/blob/47090260f170bc8382c4d77c6dbdbf67fffd2087/types/flow.go#L90) function and noticed that it only uses the source and destination port to identify flows. 

Is there any reason to base the identification exclusively on these ports? Why can't the destination and source IP be used as a way to complement this process?

If we have two different pairs of machines using the same pair of ports to communicate, the current implementation will see these communications as a single flow and not two independent flows.

**Comment by glaslos** [comment]
We use `flow.String()` which should be a string like `ip:port->ip:port` if I'm not mistaken https://github.com/google/gopacket/blob/master/flows.go#L178

**Comment by MrSuicideParrot** [comment]
The Flow type can be applied to the NetworkLayer and TransportLayer. When it is retrieved from the network layer it will be two IPs and in the case of the transport layer it will be network ports. 

> **A Flow is a simple object made up of a set of two Endpoints, one source and one destination. It details the sender and receiver of the Layer of the Packet.** An Endpoint is a hashable representation of a source or destination.   **For example, for LayerTypeIPv4, an Endpoint contains the IP address bytes for a v4 IP packet.**
[Gopacket - Flow documentation](https://godoc.org/github.com/google/gopacket#hdr-Flow_And_Endpoint) 

As [GetFlowForPacket]( https://github.com/mushorg/go-dpi/blob/47090260f170bc8382c4d77c6dbdbf67fffd2087/types/flow.go#L90) retrieves the Flow from the transport layer, the string representation will be a string like `port->port`.

To test my hypothesis, I changed the GetFlowForPacket function to print the flow string.
```golang
func GetFlowForPacket(packet gopacket.Packet) (flow *Flow, isNew bool) {
	isNew = true
	if transport := packet.TransportLayer(); transport != nil {
		gpktFlow := transport.TransportFlow()
		fmt.Println("Flow: " + gpktFlow.String()) //Change
		srcEp, dstEp := gpktFlow.Endpoints()
```
The result can be seen in the following picture. The program prints `port->port`.
![2020-01-29_21-25](https://user-images.githubusercontent.com/22855486/73398837-14f51380-42de-11ea-81ea-68323b15e849.png)
