### ISSUE TITLE
Build Error - Windows platform

### ISSUE THREAD

**Issue by srajeshinfotech** [mushorg/go-dpi#62]
Hi Team,

I'm unable to build for windows platform.

Would you please help me to resolve the issue?

MacBook-Pro:go-dpi $ **sudo GOOS=windows go build -v godpi_example/example_app.go**
github.com/mushorg/go-dpi/modules/ml
go build github.com/mushorg/go-dpi/modules/ml: build constraints exclude all Go files in /Users/rajesh/Projects/go-dpi/modules/ml
github.com/mushorg/go-dpi/modules/wrappers
#github.com/mushorg/go-dpi/modules/wrappers
modules/wrappers/wrappers.go:51:3: undefined: NewLPIWrapper
modules/wrappers/wrappers.go:52:3: undefined: NewNDPIWrapper
MacBook-Pro:go-dpi $

Best Regards,
Rajesh~
iRxTx.com
+91-9600635770

**Comment by glaslos** [comment]
Windows is not supported, notice this line:

> build constraints exclude all Go files in /Users/rajesh/Projects/go-dpi/modules/ml
