### ISSUE TITLE
E: Unable to locate package golang-1.7-go

### ISSUE THREAD

**Issue by goish135** [mushorg/go-dpi#64]
I have a question about setup Go environment (according WiKi: Installation guide)
Error message is 'Unable to locate package golang-1.7-go'
![image](https://user-images.githubusercontent.com/24766208/101258331-c5cd0a00-375c-11eb-879a-36556506a800.png)

**Comment by glaslos** [comment]
Please don't post pictures but text so text search works.
The installation instructions are a bit outdated. I updated them. Please try: `sudo apt-get install golang`

**Comment by goish135** [comment]
Thank you ! 
And I will try again to setup my Go environment .
I re-edit my post question by text and photo .

**Comment by goish135** [comment]
Hi : 
Try new command : sudo apt-get install golang
It worked !!! 
and append my version of current golang 
`go version go1.10.4 linux/amd64`
