### ISSUE TITLE
An error occurs when example_app is run in centos and files cannot be found

### ISSUE THREAD

**Issue by longpi1** [mushorg/go-dpi#67]
../modules/ml/linearsvc.go:18:21: fatal error: linear.h: No such file or directory
 // #include <linear.h>
                     ^
compilation terminated.
#github.com/mushorg/go-dpi/modules/wrappers
In file included from  ../modules/wrappers/nDPI_wrapper.go:6:0:
./nDPI_wrapper_impl.h:3:28: fatal error: ndpi/ndpi_main.h: No such file or directory
 #include <ndpi/ndpi_main.h>
                            ^
compilation terminated.

**Comment by iFANGXIE** [comment]
I also encountered this problem. What is the solution? My platform is windows……

**Comment by glaslos** [comment]
Hi @longpi1 you are missing the `liblinear` library which is a dependency for building go-dpi.
