### ISSUE TITLE
An unknown error occurred when I ran godpi, but I don't know how to solve it. I hope to seek your help. Thank you very much

### ISSUE THREAD

**Issue by iFANGXIE** [mushorg/go-dpi#68]
#github.com/mushorg/go-dpi/modules/wrappers
..\..\pkg\mod\github.com\mushorg\go-dpi@v0.0.0-20211208165208-05000d80b411\modules\wrappers\nDPI_wrapper.go:61:24: could not determine kind of name for C.__time_t
cgo: 
gcc errors for preamble:
In file included from C:/msys64/mingw64/include/ndpi_main.h:32,
                 from ./nDPI_wrapper_impl.h:3,
                 from ..\..\pkg\mod\github.com\mushorg\go-dpi@v0.0.0-20211208165208-05000d80b411\modules\wrappers\nDPI_wrapper.go:6:
C:/msys64/mingw64/include/ndpi_define.h:362:1: error: stray '@' in program
  362 | @HANDLE_TLS_SIGS@#define TLS_HANDLE_SIGNATURE_ALGORITMS 1
      | ^
C:/msys64/mingw64/include/ndpi_define.h:362:17: error: stray '@' in program
  362 | @HANDLE_TLS_SIGS@#define TLS_HANDLE_SIGNATURE_ALGORITMS 1
      |                 ^
C:/msys64/mingw64/include/ndpi_define.h:362:18: error: stray '#' in program
  362 | @HANDLE_TLS_SIGS@#define TLS_HANDLE_SIGNATURE_ALGORITMS 1
      |                  ^
C:/msys64/mingw64/include/ndpi_define.h:362:2: error: unknown type name 'HANDLE_TLS_SIGS'
  362 | @HANDLE_TLS_SIGS@#define TLS_HANDLE_SIGNATURE_ALGORITMS 1
      |  ^~~~~~~~~~~~~~~
C:/msys64/mingw64/include/ndpi_define.h:362:26: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'TLS_HANDLE_SIGNATURE_ALGORITMS'
  362 | @HANDLE_TLS_SIGS@#define TLS_HANDLE_SIGNATURE_ALGORITMS 1
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by JohnHammond** [comment]
@iFANGXIE I see you created you this issue but closed it without any further details. How had you resolved this?

**Comment by HFANFA** [comment]
You can follow the installation guide in the wiki, nDPI requires version 3.2, but I chose the latest version and it caused problems, and it was resolved after following the guide. Wish you well！
