### ISSUE TITLE
An error occurs when example_app is running

### ISSUE THREAD

**Issue by iFANGXIE** [mushorg/go-dpi#69]
# github.com/mushorg/go-dpi/modules/wrappers
nDPI_wrapper_impl.c: In function 'ndpiInitialize':
nDPI_wrapper_impl.c:71:20: warning: implicit declaration of function 'ndpi_detection_get_sizeof_ndpi_id_struct'; did you mean 'ndpi_detection_get_sizeof_ndpi_flow_struct'? [-Wimplicit-function-declaration]
   71 |   size_id_struct = ndpi_detection_get_sizeof_ndpi_id_struct();
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                    ndpi_detection_get_sizeof_ndpi_flow_struct
nDPI_wrapper_impl.c: In function 'packet_processing':
nDPI_wrapper_impl.c:210:30: error: too many arguments to function 'ndpi_detection_process_packet'
  210 |     ndpi_protocol detected = ndpi_detection_process_packet(ndpi_struct, ndpi_flow, (uint8_t *) iph, ipsize, time, src, dst);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/msys64/mingw64/include/ndpi_main.h:35,
                 from nDPI_wrapper_impl.h:3,
                 from nDPI_wrapper_impl.c:5:
C:/msys64/mingw64/include/ndpi_api.h:326:17: note: declared here
  326 |   ndpi_protocol ndpi_detection_process_packet(struct ndpi_detection_module_struct *ndpi_struct,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by glaslos** [comment]
Which ndpi version are you using? If you follow the [guide](https://github.com/mushorg/go-dpi/wiki/Installation-guide#optional), you should be on 3.2-stable

**Comment by glaslos** [comment]
It also has the instructions on how to disable the usage of ndpi

**Comment by iFANGXIE** [comment]
Thank you for your answer. I will try to solve the problem immediately
