### ISSUE TITLE
wand.net.nz

### ISSUE THREAD

**Issue by shamooosa** [mushorg/go-dpi#70]
domain wand.net.nz is down .. so i cant get packages of even neat support

**Comment by glaslos** [comment]
Hey, one option for now would be installing libprotoident from the source: https://github.com/LibtraceTeam/libprotoident

**Comment by glaslos** [comment]
There is also a package available from here: https://cloudsmith.io/~wand/repos/libprotoident/packages/

**Comment by glaslos** [comment]
Fix merged. Try the latest version.
