### ISSUE TITLE
run example_app.go. at GoLand occurred error

### ISSUE THREAD

**Issue by ren2881971** [mushorg/go-dpi#73]
![image](https://user-images.githubusercontent.com/2144146/216266170-2603704d-7201-4af5-9b9d-319d0634b6e5.png)

Hellp， when i run example_app.go. at GoLand occurred error,
how to fix this problem. i need installed ndpi?  
env:  MacOS 13.0.1  M1
go:1.19.2

 github.com/mushorg/go-dpi/modules/ml
../modules/ml/linearsvc.go:18:11: fatal error: 'linear.h' file not found
 #include <linear.h>
          ^~~~~~~~~~
1 error generated.
 github.com/mushorg/go-dpi/modules/wrappers
In file included from ../modules/wrappers/nDPI_wrapper.go:6:
./nDPI_wrapper_impl.h:3:10: fatal error: 'ndpi/ndpi_main.h' file not found
#include <ndpi/ndpi_main.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by glaslos** [comment]
You have to follow the installation instructions: https://github.com/mushorg/go-dpi/wiki/Installation-guide
